### ISSUE TITLE
Using powershell for downloading is broken when calling julia from inside mintty.

### ISSUE THREAD

**Issue by twadleigh** [JuliaPackaging/BinDeps.jl#167]
I am testing [wrapping `julia` in the `mintty` terminal emulator for windows](https://github.com/JuliaLang/julia/pull/12879). In that case, using powershell for downloads in `download_cmd` causes a hang. Removing `:powershell`, it worked fine with `curl` for me.

**Comment by tkelman** [comment]
I'm having a hard time reproducing this.

**Comment by twadleigh** [comment]
I can't reproduce it on the loaner laptop I have right now, either. I'll try again on my work machine when I'm back in the office next week.

**Comment by twadleigh** [comment]
On my machine I'm able to reproduce this by:
 1. deleting the `usr` and `downloads` directories under `Images/deps`;
 2. executing `Pkg.build("Images")` from mintty-wrapped julia.

`BinDeps` hangs [here](https://github.com/JuliaLang/BinDeps.jl/blob/c34d70cbe3d31c87f81475a07c9cad1441d64df5/src/BinDeps.jl#L473) while executing the command:
```
`powershell -Command '(new-object net.webclient).DownloadFile("http://www.imagemagick.org/download/binaries/ImageMagick-6.9.2-0-Q16-x64-dll.exe", "C:\tw\v0.4\Images\deps\downloads\ImageMagick-6.9.2-0-Q16-x64-dll.exe")'`
```
The download completes, but the `run` never returns.

**Comment by twadleigh** [comment]
I'm hoping this ends up having the same root cause as the "`Ctrl+C` in a subprocess kills `mintty`" problem, so that one fix addresses both outstanding issues.

Unfortunately, this seems to boil down to subtlies with `spawn`, which puts it outside of my comfort zone. I might be able to push this forward with some help, but I'm otherwise at an impasse.

**Comment by tkelman** [comment]
@twadleigh or anyone else who was able to reproduce this, can you remind me what version of Windows you were using when you saw this? The Images download presumably needs to be ImageMagick now.

**Comment by twadleigh** [comment]
Win 7
