### ISSUE TITLE
suppress output from unpack_cmd

### ISSUE THREAD

**Issue by musm** [JuliaPackaging/BinDeps.jl#274]
I find it annoying that `unpack_cmd` dumps the extraction info to julia, typically many pages. Would it be possible to pipe this information into a logfile of the extraction folder instead of having it pollute the julia repl and dump pages of extraction details of a dep?

**Comment by tkelman** [comment]
It's possible to suppress output unless there's a problem, see how WinRPM does it. But it is kind of messy to do.
