### ISSUE TITLE
move to JuliaPackaging?

### ISSUE THREAD

**Issue by vtjnash** [JuliaPackaging/BinDeps.jl#304]
~https://github.com/JuliaInterop : "Easy interoperability between Julia and not Julia"~

https://github.com/JuliaPackaging: "Simplifying working with Julia packages and dependencies since 2016"

**Comment by tkelman** [comment]
I was thinking more JuliaPackaging

**Comment by stevengj** [comment]
Ah, nevermind, I just needed to type "BinDeps.jl" rather than "BinDeps" as the repo name.
