### ISSUE TITLE
Malformed shell commands on Windows with 0.7 master 

### ISSUE THREAD

**Issue by amellnik** [JuliaPackaging/BinDeps.jl#340]
This shows up when installing ZMQ (https://github.com/JuliaInterop/ZMQ.jl/issues/159#issuecomment-347591540), but I think this is a BinDeps issue.  `@BinDeps.install` produces a malformed shell command (see the last argument) under 0.7 but not 0.6:

```julia
LoadError: failed process: Process(`'C:\Users\amellnik\AppData\Local\Julia-0.7.0-DEV\bin\7z.exe' x -y 
'C:\Users\amellnik\.julia\v0.7\WinRPM\cache\2\noarch%2Fmingw64-libwinpthread1-5.0.3-1.2.noarch.cpio' 
'-oC:\Users\amellnik\.julia\v0.7\WinRPM\deps'`, ProcessExited(2)) [2]
in expression starting at C:\Users\amellnik\.julia\v0.7\ZMQ\deps\build.jl:36
```

**Comment by ararslan** [comment]
So this wasn't happening on 0.6? It looks to me like it gets parsed the same way:
```julia
julia> `7z.exe x C:\\somefile.txt -y -oC:\\dir`
`7z.exe x 'C:\somefile.txt' -y '-oC:\dir'`
```
(Note the quotes around the entire output directory specification)

**Comment by tkelman** [comment]
There's nothing wrong with the command here at all. Windows can't replace in-use dlls. Close all julia executables, jupyter notebooks, etc and reboot for good measure, then try again without any changes to bindeps.

**Comment by amellnik** [comment]
The issue I was seeing appears to be related to unusual characters (like +) in filenames and urls: https://github.com/JuliaPackaging/WinRPM.jl/issues/134#issuecomment-350423390
