### ISSUE TITLE
Libdl undefined on Julia v0.7

### ISSUE THREAD

**Issue by andyferris** [JuliaPackaging/BinDeps.jl#351]
I have no idea if this is relevant to particular packages or to BinDeps, but I'm having trouble building Blosc and HDF5 on Julia v0.7 (on a Ubuntu 17.10 machine). The problem seems to be fixed if I add `using Libdl` to the `build.jl` scripts of either package.

It seems that `Base.Libdl` used to be exported (as the binding to the module) from `Base` but now it is a stdlib.

**Comment by musm** [comment]
stale
