### ISSUE TITLE
v1.0 status ?

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaPackaging/BinDeps.jl#384]
What's the status on v1.0 compatibility ? Is someone working on it ? I could maybe do some work otherwise.

**Comment by timholy** [comment]
Very kind offer. Are you aware that the future is [BinaryBuilder](https://github.com/JuliaPackaging/BinaryBuilder.jl) and [BinaryProvider](https://github.com/JuliaPackaging/BinaryProvider.jl)? (In the short term migrating a package's build script could be more work, of course, but the satisfaction level with the Binary* packages seems very high from what I can see.)

**Comment by jonathanBieler** [comment]
Yes I know about it (I haven't managed to use it yet though). That said BinDeps.jl is used by a lot of packages at the moment, I don't think we can afford not to update it.

**Comment by eschnett** [comment]
Would it make sense to add pointers to BinaryBuilder and BinaryProvider to the BinDeps README?

**Comment by jonathanBieler** [comment]
BinDeps seems to be up-to-date for the most part, the issue is rather that the packages is uses for testing are not.

**Comment by musm** [comment]
donehttps://github.com/JuliaPackaging/BinDeps.jl/releases
