### ISSUE TITLE
Package maintenance / Rights

### ISSUE THREAD

**Issue by lobingera** [JuliaPackaging/BinDeps.jl#398]
@JuliaPackaging @Keno @staticfloat @tkelman @vtjnash 

Do you have a proposal how to deal with un-merged PRs in BinDeps?
Would you accept some users with write access to JuliaPackaging, so we can merge at least some of the PRs and bring back testing.

**Comment by staticfloat** [comment]
We solved this by adding @lobingera as a collaborator to the project.
